site_name: Production ready Odoo SaaS based on Kubernetes
theme:
  name: readthedocs
  highlightjs: true
plugins:
  - search
  - mkdocstrings:
      handlers:
        # See: https://mkdocstrings.github.io/python/usage/
        python:
          options:
            docstring_style: sphinx
markdown_extensions:
  - markdown_include.include:
      base_path: .
  - admonition


nav:
  - Home: 'index.md'
  - Setup Manager Instance: 'index.md'
  - Setup K8s Cluster: 'index.md'
